### ISSUE TITLE
How to use keep and keep-with-next

### ISSUE THREAD

**Issue by GoogleCodeExporter** [joeha480/dotify#101]
```
See example test at 
https://github.com/snaekobbi/pipeline-mod-braille/blob/cea79f8bcbcd907a13dc0b906
84e9ce01de47c29/pipeline-braille-utils/dotify/dotify-formatter/src/test/xprocspe
c/test_obfl-to-pef.xprocspec#L234

The actual output is as if the "keep" and "keep-with-next" attributes weren't 
there. So I think I'm not using them correctly.
```

Original issue reported on code.google.com by `bertfrees` on 7 Jan 2015 at 2:13

**Comment by bertfrees** [comment]
It seems like this is a bug. @joeha480 is going to have a look.

**Comment by joeha480** [comment]
Keep does not apply to paragraphs, only text nodes. To get the behavior you're looking for, you have to have a paragraph that spans multiple lines, e.g.

		<block break-before="page">
			<block>⠤⠤⠤</block>
			<block>⠤⠤⠤</block>
			<block>⠤⠤⠤</block>
			<block>⠤⠤⠤</block>
			<block keep="all">⠤⠤⠤ ⠤⠤⠤ ⠤⠤⠤ ⠤⠤⠤ ⠤⠤⠤ ⠤⠤⠤ ⠤⠤⠤ ⠤⠤⠤ </block>
		</block>

**Comment by bertfrees** [comment]
Keeping multiple blocks together doesn't seem to work yet?

    <block keep="all" keep-with-next="1">⠤⠤⠤</block>
    <block keep="all" keep-with-next="1">⠤⠤⠤</block>
    <block keep="all" keep-with-next="1">⠤⠤⠤</block>
    <block keep="all">⠤⠤⠤</block>

**Comment by joeha480** [comment]
@bertfrees OK to close?

**Comment by bertfrees** [comment]
Yep
