### ISSUE TITLE
Row gap and bottom-margin

### ISSUE THREAD

**Issue by joeha480** [joeha480/dotify#132]
From @jukkae:

If there’s nested blocks so that the inner block has row-spacing other than 1, and the outer block has margin-bottom, the inner block’s row-spacing affects also outer block’s margin. To illustrate, I have the following OBFL:

            <block margin-bottom="1">
              <block row-spacing="2.0">⠿⠿⠿⠿⠿⠿⠿⠿ ⠿⠿⠿⠿⠿⠿⠿⠿</block>
            </block>
            <block margin-top="1" margin-bottom="1">
              <block row-spacing="2.0">⠿⠿⠿⠿⠿⠿⠿⠿ ⠿⠿⠿⠿⠿⠿⠿⠿</block>
            </block>
            <block margin-top="1">
              <block row-spacing="2.0">⠿⠿⠿⠿⠿⠿⠿⠿ ⠿⠿⠿⠿⠿⠿⠿⠿</block>
            </block>

The OBFL is transformed into following PEF:

            <page>
                <row rowgap="4">⠿⠿⠿⠿⠿⠿⠿⠿⠀⠿⠿⠿⠿⠿⠿⠿⠿</row>
                <row rowgap="4"/>
                <row/>
                <row rowgap="4">⠿⠿⠿⠿⠿⠿⠿⠿⠀⠿⠿⠿⠿⠿⠿⠿⠿</row>
                <row rowgap="4"/>
                <row/>
                <row>⠿⠿⠿⠿⠿⠿⠿⠿⠀⠿⠿⠿⠿⠿⠿⠿⠿</row>
            </page>

IIUC, the empty rows that currently have rowgap=”4” shouldn’t have that attribute at all. Furthermore, what’s interesting is that the blank rows generated from top margin don’t get the erroneous rowgap attribute. Have you ran into anything similar before? I haven’t done more extensive testing, nor have I looked at the source code, but from what I’ve seen thus far, it seems that margin sizes or row-spacing don’t affect the behavior at all, row-spacing still bleeds through to rowgap in the row generated from outer block’s margin.

**Comment by joeha480** [comment]
I have found the issue. Actually, it was two different issues.

One was in the propagation of block properties, which didn’t happen the way it was supposed to. Upon fixing this issue, the symptom moved from the bottom margin to the top!

Then I found that the implementation of collapsing margins assumed that all margin candidates have equal row spacing. The margin was then simply assigned to the block that was “closest”, and it got whatever row spacing that block had.

These issues are now resolved and will be pushed shortly. I will release dotify.formatter.impl:1.1.3 later today or tomorrow.

Thank you for finding these issues!

Note that, due to the collapsing margin rule, the result of the above example will be:

        <page>
            <row rowgap="4">⠿⠿⠿⠿⠿⠿⠿⠿⠀⠿⠿⠿⠿⠿⠿⠿⠿</row>
            <row/>
            <row rowgap="4">⠿⠿⠿⠿⠿⠿⠿⠿⠀⠿⠿⠿⠿⠿⠿⠿⠿</row>
            <row/>
            <row>⠿⠿⠿⠿⠿⠿⠿⠿⠀⠿⠿⠿⠿⠿⠿⠿⠿</row>
        </page>

**Comment by bertfrees** [comment]
Thanks! Jukka will try it tomorrow.

**Comment by bertfrees** [comment]
@joeha480 The update to dotify.formatter.impl 1.1.3 seems to have broken something: see https://github.com/daisy/pipeline-mod-braille/commit/c8ec55a3f9110506feb88fcb23cf50131f60e0d1. I have included in the new version anyway, but can you investigate what is wrong?
