### ISSUE TITLE
Fix Eclipse project files?

### ISSUE THREAD

**Issue by bertfrees** [joeha480/dotify#137]
The Eclipse files that are checked in didn't work for me. What fixed it for me was to add `apply plugin: "eclipse"` to the gradle file, then remove all `.project` and `.classpath` files and run `gradle eclipse`.

In `.classpath`, entries like these
```
<classpathentry kind="con" path="aQute.bnd.classpath.container"/>
```
are now replaced by entries like:
```
<classpathentry sourcepath="/Users/bert/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/annotation/2.3.0/75c10014ae2d6b0dfce8be89d0763f33ce189861/annotation-2.3.0-sources.jar" kind="lib" path="/Users/bert/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/annotation/2.3.0/6359968e37016dc2686378d029bca7bfb73e0abc/annotation-2.3.0.jar"/>
```

Of course we can't check in these files. Either the checked in files should work or they should be deleted and instructions for generating them added to the developer doc.

**Comment by joeha480** [comment]
Which version of Eclipse are you using? They could also be outdated.

**Comment by bertfrees** [comment]
Luna

**Comment by joeha480** [comment]
Try with Mars.
