### ISSUE TITLE
Behavior of scope=spread on first page of sequence

### ISSUE THREAD

**Issue by bertfrees** [joeha480/dotify#143]
Joel says `scope="spread"` currently does not search beyond the boundaries of sequences. We discussed this briefly and the conclusion was that it is desirable to search beyond the boundaries of sequences but probably not the boundaries of volumes. The idea is to change the behavior of `scope="spread"` accordingly. Possibly we can add new values for `scope`, such as `spread-within-sequence` or `spread-within-page-type`.

**Comment by bertfrees** [comment]
The first part, "desirable to search beyond the boundaries of sequences", doesn't seem to be working yet: see the test [marker-reference-spread-across-sequence](https://rawgit.com/snaekobbi/dotify/168c50fe265c9b007cf5557b95b0b1bf4fe44201/dotify.formatter.impl/test/org.daisy.dotify.engine.impl.resource-files.tests-overview.html#dp2/marker-reference-spread-across-sequence-input.obfl).

**Comment by joeha480** [comment]
I think you should make a new issue, apparently I have implemented and tested for this case, see https://rawgit.com/joeha480/dotify/master/dotify.formatter.impl/test/org.daisy.dotify.engine.impl.resource-files.tests-overview.html#marker-ref-spread-sequence-input.obfl

Too bad I didn't get your test cases a month ago when I was working on it. Could we try to do better going forward? I think it would save a lot of time.

**Comment by bertfrees** [comment]
Yes, we can definitely do better. This is also the reason I've been cleaning up the tests last week: I was starting to loose the overview of what was tested and what not. So I added proper labels and descriptions. Also because most of the tests were for the combination "css-to-obfl" + "obfl-to-pef", I have deleted a bunch of tests and added a bunch of new ones more specific to the obfl-to-pef part only. The whole cleanup took me quite a lot of time actually.

**Comment by joeha480** [comment]
Thanks! That sounds great.

If I were better at writing tests, that would also help. ;-) I realize now that my test isn't testing the spread scope, only the offset (at least I think that's the case, I haven't actually looked at the file again). Damn. Well, if you want to have a look at fixing this, that would be great (I am hoping that I just missed something trivial). Otherwise I'll have a look when I can, but I'd like to complete the tables work first, but we can talk about it on Monday.

**Comment by bertfrees** [comment]
Yes, please keep focusing on tables, and volumes after that. I will have a look at everything else (and will ask you for pointers once in a while).

**Comment by bertfrees** [comment]
Seems like this has been fixed now. Did you do something?
