### ISSUE TITLE
Add option to disable upper case markers

### ISSUE THREAD

**Issue by joeha480** [joeha480/dotify#156]
It would be useful if there were an option in the translator to disable upper case markers (and a UI option to go with it). While this could be handled in pre-processing (i.e. be an option in the input -> obfl conversion), it would be useful if this could be a user preference.

**Comment by bertfrees** [comment]
Would this be a "mode"? Or a "translate" attribute? Or a "style"? Or something else?

In the CSS-based scripts either the mode is used, namely when you select a translator (for the whole document) that has upper case markers disabled,  or the style attribute is used, namely when you specify (with `text-transform:lowercase`) that only for certain parts of the document upper case markers should be disabled. 

You could do something similar. The alternative is to support parameters in the OBFL-to-PEF step that passed on to the translator. This feature could be used in both CSS-based and Dotify/XSLT based scripts. Parameters are already supported in the CSS-based scripts, but they are only passed on up to the CSS-to-OBFL level, not to the OBFL-to-PEF level. Currently there are two parameters: "duplex" and "skip-margin-top-of-page".
