### ISSUE TITLE
Support style in the formatter interface

### ISSUE THREAD

**Issue by joeha480** [joeha480/dotify#188]
Translators can process styles, but the formatter interface does not allow passing that information, forcing the style processing to be done outside of the formatter.

**Comment by joeha480** [comment]
Done, now this remains:
https://github.com/joeha480/dotify/issues/118

**Comment by bertfrees** [comment]
I actually wanted to tackle #118 some time ago, but hit a problem. That problem is probably what you have fixed now in the API.
