### ISSUE TITLE
Use MetaDataItem for identifier and date in PEFMediaWriter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [joeha480/dotify#72]
```
In PEFMediaWriter, identifier and date can be set by passing a set of 
properties to the constructor. However, there is also a MetaDataItem on the 
open method where it appears to be possible to set these. The current 
implementation will however ignore them if present in the MetaDataItem set. 
This is counter-intuitive and confusing.

```

Original issue reported on code.google.com by `joel.hak...@mtm.se` on 12 Nov 2013 at 8:22

**Comment by joeha480** [comment]
Related to #122

**Comment by joeha480** [comment]
The identifier is set via setFeature on the factory, which doesn't make sense at all, since it might be used for several instances of PagedMediaWriter. It makes more sense to use the open method on PageMediaWriter to set the metadata.
